### PR TITLE
CardinalityEstimatorSerializer: expose BinaryReader/Writer as input f…

### PR DESCRIPTION
**Pull request by olegsavin**
…or serialization.

### CODE REVIEW

**Review by pshrosbree — APPROVED** [review]

**Comment by pshrosbree** [comment]
You should bump the package version as well.

**Review by oronnavon — APPROVED** [review]
Looks good. Please bump the Nuget package version to 1.5 (see https://github.com/Microsoft/CardinalityEstimation/blob/master/CardinalityEstimation/CardinalityEstimation.nuspec) and try to publish a new NuGet package. If this gives you any trouble, let me know and I'll publish.

**Comment by olegsavin** [comment]
@oronnavon, please merge it, I don't have permissions. I will publish nuget from master branch after that. Thanks!

**Comment by oronnavon** [comment]
@olegsavin looks like I've lost write permissions to this repo since leaving Microsoft. Also I'm surprised you don't have write permissions yourself - can you or @pshrosbree please add me as an external collaborator to this repo, as per https://help.github.com/articles/adding-outside-collaborators-to-repositories-in-your-organization/ ? Thanks. Note I've published an updated NuGet package

**Comment by olegsavin** [comment]
Turns out @selvasingh is admin, sent request to him.

**Pull request merged**
